/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/VUoxVK9P424
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'
import { Rubik } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState } from "react"
import Link from "next/link"
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"

export function Document() {
  const [documentImages, setDocumentImages] = useState([])
  const [showChatbot, setShowChatbot] = useState(false)
  const handleImageUpload = (event) => {
    const files = event.target.files
    const base64Images = []
    for (let i = 0; i < files.length; i++) {
      const file = files[i]
      const reader = new FileReader()
      reader.onload = () => {
        base64Images.push(reader.result)
        setDocumentImages(base64Images)
      }
      reader.readAsDataURL(file)
    }
  }
  return (
    (<div className="flex flex-col min-h-[100dvh]">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link href="#" className="flex items-center justify-center" prefetch={false}>
          <FileIcon className="h-6 w-6" />
          <span className="sr-only">Document Analysis Service</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link
            href="#"
            className="text-sm font-medium hover:underline underline-offset-4"
            prefetch={false}>
            Features
          </Link>
          <Link
            href="#"
            className="text-sm font-medium hover:underline underline-offset-4"
            prefetch={false}>
            Pricing
          </Link>
          <Link
            href="#"
            className="text-sm font-medium hover:underline underline-offset-4"
            prefetch={false}>
            About
          </Link>
          <Link
            href="#"
            className="text-sm font-medium hover:underline underline-offset-4"
            prefetch={false}>
            Contact
          </Link>
        </nav>
      </header>
      <main className="flex-1 flex flex-col gap-8 p-6 md:p-10">
        <Card>
          <CardHeader>
            <CardTitle>Annual Report 2023</CardTitle>
            <CardDescription>Last updated 2 days ago</CardDescription>
          </CardHeader>
          <CardContent>
            <p>A detailed analysis of the company's financial performance in 2023.</p>
            <div className="grid grid-cols-3 gap-4 mt-4">
              {documentImages.map((image, index) => (
                <img
                  key={index}
                  src="/placeholder.svg"
                  alt={`Document Image ${index + 1}`}
                  width={200}
                  height={200}
                  className="object-contain"
                  style={{ aspectRatio: "200/200", objectFit: "cover" }} />
              ))}
            </div>
            <div className="flex justify-end gap-2 mt-4">
              <input
                type="file"
                multiple
                className="hidden"
                id="document-images"
                onChange={handleImageUpload} />
              <label
                htmlFor="document-images"
                className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50">
                Upload Images
              </label>
              <Button variant="outline" onClick={() => setShowChatbot(true)}>
                Chat with Chatbot
              </Button>
            </div>
          </CardContent>
        </Card>
      </main>
      {showChatbot && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/50">
          <Card className="w-full max-w-4xl">
            <CardHeader>
              <CardTitle>Chat with Chatbot</CardTitle>
              <CardDescription>Discuss the details of the Annual Report 2023</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid gap-4">
                <div className="flex items-start gap-4">
                  <Avatar>
                    <AvatarImage src="/placeholder-user.jpg" alt="Chatbot" />
                    <AvatarFallback>CB</AvatarFallback>
                  </Avatar>
                  <div className="flex-1 bg-muted rounded-lg p-4">
                    <p>Hello, I'm the Document Analysis Chatbot. How can I assist you with the Annual Report 2023?</p>
                  </div>
                </div>
                <div className="flex items-start gap-4">
                  <Avatar>
                    <AvatarImage src="/placeholder-user.jpg" alt="User" />
                    <AvatarFallback>U</AvatarFallback>
                  </Avatar>
                  <div className="flex-1 bg-muted rounded-lg p-4">
                    <p>
                      I'd like to get a high-level overview of the key financial metrics and performance highlights from
                      the report.
                    </p>
                  </div>
                </div>
                <div className="flex items-start gap-4">
                  <Avatar>
                    <AvatarImage src="/placeholder-user.jpg" alt="Chatbot" />
                    <AvatarFallback>CB</AvatarFallback>
                  </Avatar>
                  <div className="flex-1 bg-muted rounded-lg p-4">
                    <p>Certainly, let me summarize the key highlights from the Annual Report 2023:</p>
                    <ul className="list-disc pl-4 mt-2">
                      <li>Revenue grew by 15% year-over-year, reaching $250 million</li>
                      <li>Net income increased by 20%, totaling $35 million</li>
                      <li>The company expanded its customer base by 25%, adding 500 new clients</li>
                      <li>Research and development investments increased by 18%, driving innovation</li>
                      <li>The company's cash reserves grew by 30%, strengthening its financial position</li>
                    </ul>
                  </div>
                </div>
                <div className="flex items-start gap-4">
                  <Avatar>
                    <AvatarImage src="/placeholder-user.jpg" alt="User" />
                    <AvatarFallback>U</AvatarFallback>
                  </Avatar>
                  <div className="flex-1 bg-muted rounded-lg p-4">
                    <p>
                      That's very helpful, thank you. Can you also provide some insights on the company's growth
                      strategy and market positioning?
                    </p>
                  </div>
                </div>
                <div className="flex items-start gap-4">
                  <Avatar>
                    <AvatarImage src="/placeholder-user.jpg" alt="Chatbot" />
                    <AvatarFallback>CB</AvatarFallback>
                  </Avatar>
                  <div className="flex-1 bg-muted rounded-lg p-4">
                    <p>Absolutely, the report highlights the company's focus on the following growth strategies:</p>
                    <ul className="list-disc pl-4 mt-2">
                      <li>Expanding into new geographic markets, particularly in Europe and Asia</li>
                      <li>Launching new product lines to diversify the company's offerings</li>
                      <li>Investing in digital transformation and automation to improve operational efficiency</li>
                      <li>Strengthening the company's brand and market positioning as a leader in the industry</li>
                    </ul>
                  </div>
                </div>
                <div className="flex items-start gap-4">
                  <Avatar>
                    <AvatarImage src="/placeholder-user.jpg" alt="User" />
                    <AvatarFallback>U</AvatarFallback>
                  </Avatar>
                  <div className="flex-1 bg-muted rounded-lg p-4">
                    <p>
                      That's great, thank you for the detailed overview. I think I have a good understanding of the
                      report now.
                    </p>
                  </div>
                </div>
                <div className="flex items-start gap-4">
                  <Avatar>
                    <AvatarImage src="/placeholder-user.jpg" alt="Chatbot" />
                    <AvatarFallback>CB</AvatarFallback>
                  </Avatar>
                  <div className="flex-1 bg-muted rounded-lg p-4">
                    <p>
                      You're welcome! I'm glad I could provide a helpful summary of the key information from the Annual
                      Report 2023. Please let me know if you have any other questions.
                    </p>
                  </div>
                </div>
              </div>
            </CardContent>
            <CardFooter>
              <Button variant="outline" onClick={() => setShowChatbot(false)}>
                Close
              </Button>
            </CardFooter>
          </Card>
        </div>
      )}
      <footer
        className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-muted-foreground">&copy; 2024 Document Analysis Service. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link
            href="#"
            className="text-xs hover:underline underline-offset-4"
            prefetch={false}>
            Privacy Policy
          </Link>
          <Link
            href="#"
            className="text-xs hover:underline underline-offset-4"
            prefetch={false}>
            Terms of Service
          </Link>
        </nav>
      </footer>
    </div>)
  );
}

function FileIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z" />
      <path d="M14 2v4a2 2 0 0 0 2 2h4" />
    </svg>)
  );
}
